apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name  }}-postgres
  labels:
    app: {{ .Release.Name  }}-postgres
spec:
  serviceName: {{ .Release.Name  }}-postgres-service
  selector:
    matchLabels:
      app: {{ .Release.Name  }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name  }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: POSTGRES_DB
              value: marketplace
          volumeMounts:
            - name: {{ .Release.Name  }}-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: {{ .Release.Name  }}-postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name  }}-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name  }}-postgres-service
  labels:
    app: {{ .Release.Name  }}-postgres-service
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: postgres
