kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name  }}-postgres-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi