apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name  }}-ingress
spec:
  rules:
    - http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name  }}-marketplace-service
              port:
                  number: 9000
        - path: /rate
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name  }}-rate-service
              port:
                  number: 8080
        - path: /email
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name  }}-mail-service
              port:
                number: 8085
