apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-service
  labels:
    app: rate
spec:
  selector:
    matchLabels:
      app: rate
  template:
    metadata:
      labels:
        app: rate
    spec:
      containers:
        - name: rate
          image: kocichca152/rate:latest
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
       - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rate-service
  labels:
    app: rate
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
